### ISSUE TITLE
OSError: unknown compression record

### ISSUE THREAD

**Issue by allenea** [aarande/nexradaws#11]
Hi,

I am getting an error similar to https://github.com/ARM-DOE/pyart/issues/499 

nexradaws                 1.1                      pypi_0    pypi
arm_pyart                 1.11.0           py37h3b54f70_0    conda-forge

I have 4 cases where I am trying to get and plot radar data. I think it's more likely to be a nexradaws issue rather than a pyart issue, but I am not sure. I'm looping through 4 cases where data is downloaded and plotted for each scan. It works for 3 of the 4 cases but it does not work for the June 7th, 2014 12z - June 9th, 2014 6z case from KDOX. 

###########

Downloaded KDOX20140607_121639_V07.gz
Downloaded KDOX20140607_124600_V07.gz
Downloaded KDOX20140607_123613_V07.gz
Downloaded KDOX20140607_120654_V07.gz
Downloaded KDOX20140607_122626_V07.gz
Downloaded KDOX20140607_125546_V07.gz
6 out of 6 files downloaded...0 errors
KDOX volume scan time 2014-06-07 12:06:54+00:00
KDOX volume scan time 2014-06-07 12:16:39+00:00
KDOX volume scan time 2014-06-07 12:26:26+00:00
KDOX volume scan time 2014-06-07 12:36:13+00:00
KDOX volume scan time 2014-06-07 12:46:00+00:00
KDOX volume scan time 2014-06-07 12:55:46+00:00
0 downloads failed.
[]
2014-06-07_12:00                 /Users/allenea/Documents/Eric_Allen/observation_data/Python_Programs/plots/Radar/Delaware/all_scans/pyCase_20140607/
Traceback (most recent call last):

  File "<ipython-input-11-56e5f08df9dc>", line 1, in <module>
    runfile('/Users/allenea/Documents/Eric_Allen/observation_data/Python_Programs/NEXRAD_Radar_Plotting.py', wdir='/Users/allenea/Documents/Eric_Allen/observation_data/Python_Programs')

  File "/Users/allenea/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/allenea/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/allenea/Documents/Eric_Allen/observation_data/Python_Programs/NEXRAD_Radar_Plotting.py", line 141, in <module>
    plot_radar_data(RADAR_ID, OUTDIR, CASESTUDY_TIME, RUN_TIME_DAY, RUN_TIME_HOUR)

  File "/Users/allenea/Documents/Eric_Allen/observation_data/Python_Programs/NEXRAD_Radar_Plotting.py", line 80, in plot_radar_data
    radar = scan.open_pyart()

  File "/Users/allenea/anaconda3/lib/python3.7/site-packages/nexradaws/resources/localnexradfile.py", line 56, in open_pyart
    return pyart.io.read_nexrad_archive(self.filepath)

  File "/Users/allenea/anaconda3/lib/python3.7/site-packages/pyart/io/nexrad_archive.py", line 101, in read_nexrad_archive
    nfile = NEXRADLevel2File(prepare_for_read(filename))

  File "/Users/allenea/anaconda3/lib/python3.7/site-packages/pyart/io/nexrad_level2.py", line 135, in __init__
    raise IOError('unknown compression record')

OSError: unknown compression record

**Comment by aarande** [comment]
The traceback indicates the error is in pyart and the issue you referenced seemed to cover it exactly. It sounds like some of the files in the archive may have some corruption.
