### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Aareon** [aarande/nexradaws#13]
Error when getting available scans for a timeframe and radar.

<details>
  <summary>Full Traceback</summary>

 ```
Traceback (most recent call last):
  File "C:\Users\Aareon\.virtualenvs\NEXRADAWSDataAccess-Wr4jm0uy\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Aareon\.virtualenvs\NEXRADAWSDataAccess-Wr4jm0uy\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Aareon\.virtualenvs\NEXRADAWSDataAccess-Wr4jm0uy\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Aareon\.virtualenvs\NEXRADAWSDataAccess-Wr4jm0uy\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Aareon\Desktop\NEXRADAWSDataAccess\webapp\app.py", line 51, in getData
    return getDataAWS(radarSite, ssYear, ssDay, ssMonth, ssTimeFromHR, ssTimeFromMIN, ssTimeToHR, ssTimeToMIN)
  File "C:\Users\Aareon\Desktop\NEXRADAWSDataAccess\webapp\app.py", line 21, in getDataAWS
    scans = conn.get_avail_scans_in_range(start, end, radar)
  File "C:\Users\Aareon\.virtualenvs\NEXRADAWSDataAccess-Wr4jm0uy\lib\site-packages\nexradaws\nexradawsinterface.py", line 192, in get_avail_scans_in_range 
    availscans = self.get_avail_scans('{0:0>2}'.format(day.year),
  File "C:\Users\Aareon\.virtualenvs\NEXRADAWSDataAccess-Wr4jm0uy\lib\site-packages\nexradaws\nexradawsinterface.py", line 160, in get_avail_scans
    for scan in resp.get('Contents'):
TypeError: 'NoneType' object is not iterable
```
</details>

**Comment by Aareon** [comment]
By printing the `resp`, I've found that the response does not contain any `"Contents"`.

<details>
  <summary>`resp` json</summary>

 ```
{'ResponseMetadata': {'RequestId': 'FR9EXQ716YRWTH9Q', 'HostId': '02u78j1flNyvosdo9+Z11rLb3syEOq3RrBXEWLon1oFP5GjDtktRyohYPaAF7DCMIsLZFasuuOo=', 'HTTPStatus
Code': 200, 'HTTPHeaders': {'x-amz-id-2': '02u78j1flNyvosdo9+Z11rLb3syEOq3RrBXEWLon1oFP5GjDtktRyohYPaAF7DCMIsLZFasuuOo=', 'x-amz-request-id': 'FR9EXQ716YRWT
H9Q', 'date': 'Thu, 06 Apr 2023 19:01:36 GMT', 'x-amz-bucket-region': 'us-east-1', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'serve
r': 'AmazonS3'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Marker': '', 'Name': 'noaa-nexrad-level2', 'Prefix': '2017/09/14/8/', 'Delimiter': '/', 'MaxKey
s': 1000, 'EncodingType': 'url'}
 ```
</details>
