### ISSUE TITLE
Function get_avail_scans_in_range fails when attempting to get current UTC day data.

### ISSUE THREAD

**Issue by kelsey1959** [aarande/nexradaws#4]
When attempting to retrieve a range of data for the UTC current day, the function get_avail_scans_in_range fails.  It is works correctly if you input days prior to current. Furthermore,  get_avail_scans shows available files that can be downloaded for the available range.

 Here is the error thrown.
```
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/nexradaws/nexradawsinterface.py", line 195, in get_avail_scans_in_range
    radar.upper())
  File "/usr/local/lib/python2.7/site-packages/nexradaws/nexradawsinterface.py", line 160, in get_avail_scans
    for scan in resp.get('Contents'):
TypeError: 'NoneType' object is not iterable

```
To reproduce.

```
>>> from datetime import datetime
>>> import nexradaws
>>> conn = nexradaws.NexradAwsInterface()

Look for available scans for current UTC day. In this case 05/03.
>>> scans = conn.get_avail_scans('2019', '05', '03', 'KTLX')
>>> print scans
[<AwsNexradFile object - 2019/05/03/KTLX/KTLX20190503_000406_V06>, 
<AwsNexradFile object - 2019/05/03/KTLX/KTLX20190503_001346_V06>, 
<AwsNexradFile object - 2019/05/03/KTLX/KTLX20190503_002326_V06>, 
<AwsNexradFile object - 2019/05/03/KTLX/KTLX20190503_003305_V06>, 
<AwsNexradFile object - 2019/05/03/KTLX/KTLX20190503_004245_V06>, 
<AwsNexradFile object - 2019/05/03/KTLX/KTLX20190503_005225_V06>, 
<AwsNexradFile object - 2019/05/03/KTLX/KTLX20190503_010204_V06>]

Data is available for download.
>>> results = conn.download(scans[0:7], tempdir)
Downloaded KTLX20190503_000406_V06
Downloaded KTLX20190503_001346_V06
Downloaded KTLX20190503_005225_V06
Downloaded KTLX20190503_003305_V06
Downloaded KTLX20190503_002326_V06
Downloaded KTLX20190503_004245_V06
Downloaded KTLX20190503_010204_V06
7 out of 7 files downloaded...0 errors

Set time in UTC for range that you want to download. In this case 05/03 at hour 00.
>>> start = datetime(2019,5,3,0,0)
>>> print start
2019-05-03 00:00:00
>>> end = datetime(2019,5,3,1,0)
>>> print end
2019-05-03 01:00:00

Attempt to get scans in the range start and end times.
>>> scans = conn.get_avail_scans_in_range(start, end, 'KTLX')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/nexradaws/nexradawsinterface.py", line 195, in get_avail_scans_in_range
    radar.upper())
  File "/usr/local/lib/python2.7/site-packages/nexradaws/nexradawsinterface.py", line 160, in get_avail_scans
  for scan in resp.get('Contents'):
TypeError: 'NoneType' object is not iterable
```

**Comment by tayknight** [comment]
I created a [pull-request](https://github.com/aarande/nexradaws/pull/5/commits/dc92db994e6002b8f3d36f87cfd1720f1b0ed52a) that fixed this issue for me.

**Comment by aarande** [comment]
Pull request has been merged and will be in the next release.
